PAMS-BE-18-회원조회 기능 구현
kwpu-system-integration/PAMS-Backend-API pull request #21
Opened 2019-09-23 11:56 UTC by JinHoooooou

## 개요

- User 회원정보 조회 기능 구현
  - QueryDsl 추가
  - Controller에 메소드 추가
  - Service에 메소드 추가
  - Predicate 클래스 추가
- Postman을 이용하여 Test

------

## PR 설명

- User 회원정보 조회 기능 구현

  - QueryDsl 추가
    <img src="https://user-images.githubusercontent.com/45187382/65308575-50136780-dbc5-11e9-8d25-822b69f243b9.PNG" alt="QueryDsl pom" style="zoom: 50%;" />
    pom.xml에 Dependency추가

![QueryDsl Repo](https://user-images.githubusercontent.com/45187382/65423630-7dba1400-de44-11e9-93dc-a5c8f5f1e63f.PNG)

       QuerydslPredicateExecutor를 추가하여 Repositiory가 QueryDsl을 실행 할 수 있는 인터페이스를 제공

    

  - Controller 클래스에 메소드 추가

![controller](https://user-images.githubusercontent.com/45187382/65423597-6844ea00-de44-11e9-9a60-fe581c6bdb43.PNG)

    

  - Service 클래스에 메소드 추가

![회원정보조회 service](https://user-images.githubusercontent.com/45187382/65423649-890d3f80-de44-11e9-96aa-6800dff177ff.PNG)

    Service 선언부

![회원정보조회 serviceImpl](https://user-images.githubusercontent.com/45187382/65423651-8dd1f380-de44-11e9-8ae5-3eebb89695d3.PNG)

    Service 구현부

    

  - Predicate 클래스 추가

![Predicate구현](https://user-images.githubusercontent.com/45187382/65423657-91fe1100-de44-11e9-885f-886279b9a5a1.PNG)

  - 이름, 학번, 패, 역할을 입력할 경우 - 입력한 정보와 일치하는 회원 검색
  - 입력하지 않을 경우 - 전체회원 조회

------

- Postman을 이용하여 Test

  - Test 1 - 이름 입력한 경우

![회원정보조회 test 1](https://user-images.githubusercontent.com/45187382/65423664-96c2c500-de44-11e9-8088-cfa55c3810e6.PNG)

  - Test 2 - 학번 입력한 경우

![회원정보조회 test 2](https://user-images.githubusercontent.com/45187382/65423666-99bdb580-de44-11e9-8e44-2303def23cdc.PNG)

  - Test 3 - 패 입력한 경우

![회원정보조회 test 3](https://user-images.githubusercontent.com/45187382/65423672-9cb8a600-de44-11e9-9c39-57fcabe1433f.PNG)

  - Test 4 - 역할 입력한 경우

![회원정보조회 test 4](https://user-images.githubusercontent.com/45187382/65423677-9fb39680-de44-11e9-8c7b-88fb95858f2e.PNG)

  - Test 5 - 아무것도 입력하지 않은 경우

![회원정보조회 test 5](https://user-images.githubusercontent.com/45187382/65423680-a215f080-de44-11e9-98a5-81f367bafb7b.PNG)

  - Test 6 - 없는 정보를 입력한 경우

![회원정보조회 test 6](https://user-images.githubusercontent.com/45187382/65423682-a510e100-de44-11e9-87a4-edfb140b996c.PNG)

  없는 정보를 입력할 경우, 리스트 조회는 나오지 않으나 response message가 "실패"가 나오도록 수정 할 필요가 있음.

------

## 참고자료

- QueryDsl 참고 : https://engkimbs.tistory.com/828

2019-09-24 01:43 UTC, TaeHyoungKwon requested changes
이제 어느정도 프로세스에는 많이 익숙해진듯? ㅋㅋㅋ
코드도 많이 깔끔해졌고 굳굳 고생했음 ㅋㅋ 😄 

수정사항들만 수정하고, re-request 버튼 눌러줘~

2019-09-24 01:43 UTC, TaeHyoungKwon commented on src/main/java/com/pams/user/controller/UserController.java
> +	@RequestMapping(value ="/getUserList", method = RequestMethod.GET)
조회 API 에 get 메소드를 쓴건 올바른데, PR Description상, parameter 넘기는 건 `request body` 로 하던데, 요건 GET 메소드에 맞지 않는듯

2019-09-24 01:43 UTC, TaeHyoungKwon commented on src/main/java/com/pams/user/controller/UserController.java
> +	@RequestMapping(value ="/getUserList", method = RequestMethod.GET)
![image](https://user-images.githubusercontent.com/18538418/65474519-17220e00-deb7-11e9-9c9d-883d2de7b3bc.png)

![image](https://user-images.githubusercontent.com/18538418/65474540-25702a00-deb7-11e9-808c-9ed3f7801dc6.png)

2019-09-24 01:43 UTC, TaeHyoungKwon commented on src/main/java/com/pams/user/service/UserServiceImpl.java
> +		log.info("<-------------------->");
[질문]
이 log의 용도는 무엇인가요?:smile:

2019-09-24 01:43 UTC, TaeHyoungKwon commented on src/main/java/com/pams/user/controller/UserController.java
> +	public @ResponseBody CommonResponseVO getUserList(@RequestBody User user) {
이 부분이 이상한 듯? `getUserList(@RequestBody User user)` 이 부분에서 User 객체 리턴 값을 RequestBody 형태로 paramter로 받는다는 것 같은데, 이 부분은 URL Paramter로 받도록 고쳐야 할듯~ :smile:

2019-09-24 01:44 UTC, TaeHyoungKwon commented
https://hongsii.github.io/2017/08/02/what-is-the-difference-get-and-post/

면접 준비용으로 GET, POST 참고자료 ㅋㅋ

2019-09-24 06:12 UTC, JinHoooooou commented on src/main/java/com/pams/user/service/UserServiceImpl.java
> +		log.info("<-------------------->");
제 콘솔에서 값 제대로 나오나 확인해보려고 작성한 코드인데 크게 필요없는거 같네요 😢

2019-09-24 06:14 UTC, JinHoooooou commented on src/main/java/com/pams/user/controller/UserController.java
> +	public @ResponseBody CommonResponseVO getUserList(@RequestBody User user) {
URL parameter가 `http://naver.com`의 com 뒤에 `?name=1 & grade=13`이런식으로 받는다는 말씀이세요??

2019-09-27 06:03 UTC, JinHoooooou commented
이미지를 너무 많이올리나요....?

2019-09-29 15:42 UTC, TaeHyoungKwon commented on src/main/java/com/pams/user/controller/UserController.java
> +	public @ResponseBody CommonResponseVO getUserList(@RequestBody User user) {
@JinHoooooou  ㅇㅇ 맞음 답 늦어서 죄송

2019-09-29 15:42 UTC, TaeHyoungKwon commented
> 이미지를 너무 많이올리나요....?

ㄴㄴ 괜찮 ㅋㅋ

2019-09-29 15:44 UTC, TaeHyoungKwon commented
저번에 말한 내용에 대해서 잘 수정해서 PR Descirption도 잘썼네~ 계속 저런 식으로 해주면되고, 
다른 파라미터 넘겨도, 제대로 안되는 문제 나중에 처리한다고 한거, 카드 1개 만들어주고~ 다음 작업 ㄱㄱ

2019-09-29 15:44 UTC, TaeHyoungKwon approved these changes

2019-09-30 02:18 UTC, merged